Map Streamer fallback to reflection when putAsync() throws NoSuchMethodError
This can happen when Simulator was compiled against Hazelacast 3.7+,
but Hazelcast 3.6- is used in a runtime