The internal repository paths are needed if the minor version is not published to sonatype repositories [HZ-5366] (#2325)
The internal repository paths are needed if the minor version is not
published to sonatype repositories. Hence, I added the internal
hazelcast repositories in case the requied os jars can not be
downloaded. Without this fix e.g. when trying to use version 5.5.8, it
fails with:

```
INFO  10:48:51 Downloading from temp: https://oss.sonatype.org/content/repositories/releases/com/hazelcast/hazelcast-sql/5.5.8/hazelcast-sql-5.5.8.jar
INFO  10:48:51 [INFO] ------------------------------------------------------------------------
INFO  10:48:51 [INFO] BUILD FAILURE
INFO  10:48:51 [INFO] ------------------------------------------------------------------------
INFO  10:48:51 [INFO] Total time:  2.368 s
INFO  10:48:51 [INFO] Finished at: 2026-04-01T10:48:51+03:00
INFO  10:48:51 [INFO] ------------------------------------------------------------------------
INFO  10:48:51 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:get (default-cli) on project standalone-pom: Couldn't download artifact: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: com.hazelcast:hazelcast-sql:jar:5.5.8 (absent): com.hazelcast:hazelcast-sql:jar:5.5.8 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
INFO  10:48:51 [ERROR]
INFO  10:48:51 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
INFO  10:48:51 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
INFO  10:48:51 [ERROR]
INFO  10:48:51 [ERROR] For more information about the errors and possible solutions, please read the following articles:
INFO  10:48:51 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] Failed to download artifact com.hazelcast:hazelcast-sql:5.5.8
Traceback (most recent call last):
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/bin/../src/perftest_cli.py", line 63, in <module>
    PerftestCli()
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/bin/../src/perftest_cli.py", line 37, in __init__
    getattr(self, args.command)()
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/bin/../src/perftest_cli.py", line 49, in run
    PerftestRunCli(sys.argv[2:])
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/src/simulator/perftest.py", line 545, in __init__
    perftest.run(tests_file, tags, args.skip_report, args.commit, pattern, run_label)
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/src/simulator/perftest.py", line 136, in run
    exitcode, run_path = self.run_single_test(test)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/src/simulator/perftest.py", line 178, in run_single_test
    driver_install_and_configure(driver, test, None, coordinator_params, inventory_path)
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/src/simulator/driver.py", line 47, in driver_install_and_configure
    _driver_exec(driver, "install.py", install_args)
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/src/simulator/driver.py", line 98, in _driver_exec
    result = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/drivers/driver-hazelcast5/conf//install.py", line 157, in exec
    _upload_hazelcast_jars(args, hosts)
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/drivers/driver-hazelcast5/conf//install.py", line 134, in _upload_hazelcast_jars
    _download_from_maven_repo(artifact_id, version, remote_repo)
  File "/Users/ihsan/Desktop/work/src/oss/hazelcast-simulator/drivers/driver-hazelcast5/conf//install.py", line 41, in _download_from_maven_repo
    raise Exception(f"Failed to download artifact {artifact}")
Exception: Failed to download artifact com.hazelcast:hazelcast-sql:5.5.8
```