Field type should use interface instead of concrete class.
This is a good practice anyway, but in this case it's a must.
Justification:
ConcurrentHashMap.keySet() returns KeySetView instead of Set in JKD8
 -> when you  use  JKD8 in compile-time, but JDK7- in runtime you
 get java.lang.NoSuchMethodError.

 Using  the ConcurrentMap interface instead of the ConcurrentHashMap class solves the problem.