Remove `awscli` from Docker image to fix build
[The docker build fails with a cryptic error message](https://github.com/hazelcast/hazelcast-simulator/actions/runs/26574821141/job/78291161764#step:13:263-L286):
> ImportError: cannot import name 'register_feature_id' from 'botocore.useragent' (/usr/local/lib/python3.11/dist-packages/botocore/useragent.py)

The root cause is that we install the (implicitly) latest `awscli` (via `pip`) but then subsequently install outdated dependencies (`botocore` \ `boto3`) with hardcoded versions via `requirements.txt` which are not compatible.

The Docker image doesn't (appear) to _need_ `awscli` - as such the simplest fix is just to remove it.